name: CI Ejercicios Node

on:
  push:
    branches:
      - main

jobs:
  pruebas:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 22]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar tests
        run: npm test
